"""Add UserVerification model and relationship

Revision ID: 1f6b36f6a82b
Revises: a97145941643
Create Date: 2026-02-22 15:44:22.299545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f6b36f6a82b'
down_revision: Union[str, Sequence[str], None] = 'a97145941643'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_verifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('instruction', sa.String(), nullable=False),
    sa.Column('image_key', sa.String(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('rejection_reason', sa.String(), nullable=True),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_verification_user_created', 'user_verifications', ['user_id', 'created_at'], unique=False)
    op.create_index('idx_verification_user_status', 'user_verifications', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_user_verifications_id'), 'user_verifications', ['id'], unique=False)
    op.create_index(op.f('ix_user_verifications_user_id'), 'user_verifications', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_verifications_user_id'), table_name='user_verifications')
    op.drop_index(op.f('ix_user_verifications_id'), table_name='user_verifications')
    op.drop_index('idx_verification_user_status', table_name='user_verifications')
    op.drop_index('idx_verification_user_created', table_name='user_verifications')
    op.drop_table('user_verifications')
    # ### end Alembic commands ###
