"""harden_refresh_tokens

Revision ID: a97145941643
Revises: f8ef1c9d65bb
Create Date: 2026-02-20 16:27:30.731126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a97145941643'
down_revision: Union[str, Sequence[str], None] = 'f8ef1c9d65bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_messages_conversation_id', 'conversations', ['conversation_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('replaced_by_token_hash', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('device_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('user_agent', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True))
        
        # Adjust unique index for token_hash
        batch_op.drop_index(op.f('ix_refresh_tokens_token_hash'))
        batch_op.create_index(op.f('ix_refresh_tokens_token_hash'), ['token_hash'], unique=True)
        
        # New indexes
        batch_op.create_index(op.f('ix_refresh_tokens_device_id'), ['device_id'], unique=False)
        batch_op.create_index(op.f('ix_refresh_tokens_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(op.f('ix_refresh_tokens_revoked_at'), ['revoked_at'], unique=False)
        
        # FK refresh with CASCADE
        batch_op.create_foreign_key('fk_refresh_tokens_user_id', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_constraint('fk_refresh_tokens_user_id', type_='foreignkey')
        batch_op.create_foreign_key('fk_refresh_tokens_user_id', 'users', ['user_id'], ['id'])
        
        batch_op.drop_index(op.f('ix_refresh_tokens_revoked_at'))
        batch_op.drop_index(op.f('ix_refresh_tokens_expires_at'))
        batch_op.drop_index(op.f('ix_refresh_tokens_device_id'))
        batch_op.drop_index(op.f('ix_refresh_tokens_token_hash'))
        batch_op.create_index(op.f('ix_refresh_tokens_token_hash'), ['token_hash'], unique=False)
        
        batch_op.drop_column('last_used_at')
        batch_op.drop_column('user_agent')
        batch_op.drop_column('device_id')
        batch_op.drop_column('replaced_by_token_hash')

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint('fk_messages_conversation_id', type_='foreignkey')
        batch_op.create_foreign_key('fk_messages_conversation_id', 'conversations', ['conversation_id'], ['id'])
    # ### end Alembic commands ###
